#!/usr/bin/env bash

# Examples:
#     ix hello.txt              # paste file (name/ext will be set).
#     echo Hello world. | ix    # read from STDIN (won't set name/ext).
#     ix -n 1 self_destruct.txt # paste will be deleted after one read.
#     ix -i ID hello.txt        # replace ID, if you have permission.
#     ix -d ID

set -eu

ix() {
    local -a opts
    local OPTIND OPTARG id

    if [[ -f "${HOME}/.netrc" ]]; then
        opts+=('-n')
    fi

    while getopts ':hd:i:n:' opt; do
        case "${opt}" in
            h) printf 'ix\t\t\tVisit http://ix.io for more instructions\n\n[-d ID ]\t\tDelete paste through id\n[-i ID]\t\t\tReplace id if you have permission\n[-n N]\t\t\tPaste will be deleted after one read\n\nExamples:\n\nix hello.txt\t\t\t\t# paste file (name/ext will be set).\necho Hello world. | ix\t\t\t# read from STDIN (won't set name/ext).\nix -n 1 self_destruct.txt\t\t# paste will be deleted after one read.\nix -i ID hello.txt\t\t\t# replace ID, if you have permission.\nix -d ID\n\n'; return;;
            d) opts+=('-X' 'DELETE'); curl "${opts[@]}" "ix.io/${OPTARG}"; return;;
            i) opts+=('-X' 'PUT'); id="${OPTARG}";;
            n) opts+=('-F' "read:1=${OPTARG}");;
        esac
    done
    shift "$((OPTIND - 1))"

    if [[ -t 0 ]]; then
        local filename="${1:-}"
        shift
        if [[ -n "${filename}" ]]; then
            curl "${opts[@]}" -F f:1=@"${filename}" "$@" "ix.io/${id}"
            return
        fi
        printf '^C (CTRL+C) to cancel, ^D (CTRL+D) to send.\n'
    fi
    curl "${opts[@]}" -F f:1='<-' "$@" "ix.io/${id}"
}

ix "$@"
